# Exercise 1: Means over axes

In [3]:
import numpy as np

In [15]:
def mean_for_loop(array):
    averages_array = []
    for i in array:
        current_average = 0
        for j in i:
            current_average += j
        current_average = current_average / len(i)
        averages_array.append(round(current_average, 8))
    return averages_array


def mean_vectors(array):
    array = np.array(array)
    array = array.mean(axis=1)
    array = array.round(8)
    return array

In [21]:
X =   [[ 0.9573075 ,  0.83877059,  1.51767182],
       [ 0.83782936, -0.88288659,  0.7371596 ],
       [-0.01786695,  0.83195016,  0.66394427],
       [-2.43495362, -0.5999003 , -1.40044824],
       [-0.67749399, -0.93229581,  0.4736418 ],
       [ 0.47934903,  0.90244159, -0.24246888],
       [ 1.00280715, -0.68745287, -1.08115248],
       [ 0.98143632,  0.77163722,  0.07051186],
       [ 1.10721349,  0.37520477,  0.54710493],
       [ 0.20813717, -0.56000733, -0.38301232]]
print("Mean using for loops\n")
arr = mean_for_loop(X)
print(*arr, sep="\n")
arr = []
print()
print("Mean using vectors\n")
arr = mean_vectors(X)
print(*arr, sep="\n")

Mean using for loops

1.1045833
0.23070079
0.49267583
-1.47843405
-0.378716
0.37977391
-0.25526607
0.6078618
0.67650773
-0.24496083

Mean using vectors

1.1045833
0.23070079
0.49267583
-1.47843405
-0.378716
0.37977391
-0.25526607
0.6078618
0.67650773
-0.24496083


# Exercise 2: Element-wise operations

In [4]:
def addition_for_loop(first_array, second_array):
    added_array = []
    for i, j in zip(first_array, second_array):
        added_array_row = []
        for k, l in zip(i, j):
            added_array_row.append(round(k + l, 8))
        added_array.append(added_array_row)
    return added_array


def addition_vectors(first_array, second_array):
    first_array = np.array(first_array)
    second_array = np.array(second_array)
    addition_array = first_array + second_array
    addition_array = addition_array.round(8)
    return addition_array

In [26]:
A =   [[-0.92597499,  0.43720423, -0.35210601],
       [-1.57649123, -1.07509224,  0.47516471],
       [-0.20934054,  1.02077567,  1.07644301],
       [-0.15567112, -2.55700368, -1.46401899],
       [ 0.02719893,  0.19837065,  1.85917993],
       [-0.48220856, -0.5882894 ,  0.8520666 ],
       [-0.61637754, -1.28843955,  0.21051033],
       [-0.37856032, -0.18264039, -1.66748906],
       [-1.88442764,  1.06363804, -0.73199025],
       [ 1.1067878 , -1.50124564,  0.3577191 ]]
       
B =   [[ 0.83755816, -1.00443884, -0.50455401],
       [ 0.17677451,  0.31791523,  0.87857933],
       [-0.79809369,  1.05786099,  1.23321483],
       [ 2.15225423,  0.03105143, -1.62707639],
       [-0.38475992,  0.52332967, -0.80852807],
       [-0.33078515, -0.39291109,  0.92239671],
       [-0.68534134,  1.42376764, -0.56941844],
       [-0.96316595, -0.9312169 , -0.6153402 ],
       [ 0.11725929,  0.12216484,  0.22910712],
       [-0.79512535,  1.4075714 , -0.53488747]]

print("Addition using for loop")
array = addition_for_loop(A, B)
print(*array, sep="\n")
array = []
print()
print("Addition using")
array = addition_vectors(A,B)
print(*array, sep="\n")

Addition using for loop
[-0.08841683, -0.56723461, -0.85666002]
[-1.39971672, -0.75717701, 1.35374404]
[-1.00743423, 2.07863666, 2.30965784]
[1.99658311, -2.52595225, -3.09109538]
[-0.35756099, 0.72170032, 1.05065186]
[-0.81299371, -0.98120049, 1.77446331]
[-1.30171888, 0.13532809, -0.35890811]
[-1.34172627, -1.11385729, -2.28282926]
[-1.76716835, 1.18580288, -0.50288313]
[0.31166245, -0.09367424, -0.17716837]

Addition using
[-0.08841683 -0.56723461 -0.85666002]
[-1.39971672 -0.75717701  1.35374404]
[-1.00743423  2.07863666  2.30965784]
[ 1.99658311 -2.52595225 -3.09109538]
[-0.35756099  0.72170032  1.05065186]
[-0.81299371 -0.98120049  1.77446331]
[-1.30171888  0.13532809 -0.35890811]
[-1.34172627 -1.11385729 -2.28282926]
[-1.76716835  1.18580288 -0.50288313]
[ 0.31166245 -0.09367424 -0.17716837]


# Exercise 3: Dot Product

In [7]:
def dot_product_for_loop(first_array, second_array):
    dot_product = 0
    for i, j in zip(first_array, second_array):
        product = i * j
        dot_product += product
    return dot_product


def dot_product_vectors(first_array, second_array):
    first_array = np.array(first_array)
    second_array = np.array(second_array)
    return np.dot(first_array, second_array)

In [8]:
a = [4, 2, 6, 2, 5, 7, 5, 8, 8, 4]
b = [0, 6, 15, 3, 4, 6, 10, 8, 8, 18]

print("Dot product using for loop")
product = dot_product_for_loop(a,b)
print(product)
product = 0
print()
print("Dot product using vectors")
product = dot_product_vectors(a,b)
print(product)

Dot product using for loop
420

Dot product using vectors
420


# Exercise 4: Matrix Multiplication

In [9]:
def multiply_for_loop(first_array, second_array):
    multiply_array = []
    temp_dot_product_array = []
    for k in first_array:
        multiply_array_row = []
        for i in range(len(second_array[0])):
            for j in second_array:
                temp_dot_product_array.append(j[i])
            prod = dot_product_for_loop(k, temp_dot_product_array)
            multiply_array_row.append(prod)
        multiply_array.append(multiply_array_row)
    return multiply_array


def multiply_vectors(first_array, second_array):
    first_array = np.array(first_array)
    second_array = np.array(second_array)
    return np.matmul(first_array, second_array)

In [12]:
A = [[1,2],
     [2,1]]
B = [[3],
     [1]]

print("Matrix multiply using for loop")
array = multiply_for_loop(A,B)
print(*array, sep="\n")
array = []
print()
print("Matrix multiply using vectors")
array = multiply_vectors(A,B)
print(*array, sep="\n")

Matrix multiply using for loop
[5]
[7]

Matrix multiply using vectors
[5]
[7]
